### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NorbertColon** [rojarsmith/rojar-gpu-watchdog#1]
Could you allow the time until a GPU failure is rebooted to be changed? My rig sometimes takes a while to spool up with some miners and this can trigger a restart? Maybe in a config file or passed as a command line parameter? Handy little program though! Thanks.

**Comment by rojarsmith** [comment]
Good idea, I will add command line for this feature.

**Comment by rojarsmith** [comment]
+v1.1.0 released and add this feature.
